import type { Metadata } from "next";
import { Domine } from "next/font/google";

import "./globals.css";

import BodyWithDynamicBackground from "@/components/body_dynamic_bg";
import Topbar from "@/components/topbar";

const domine = Domine({ variable: "--font-domine", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Harry's Haven",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<BodyWithDynamicBackground>
				<Topbar />
				{children}
			</BodyWithDynamicBackground>
		</html>
	);
}
